In [164]:
#ek thre se llist se me same thre ke data types ho
import numpy as np

In [165]:
#making variabels
d1 = [1,2,3,4,5,3]
d2 = [6,7,8,9,0,2]
d3 = [2,3,4,5,2,1]
d4 = [5,2,7,8,1,5]
dic = {1:"A",2:"b",3:"c",4:"d"}

In [166]:
#Function for 1d and 2d making array
a1 = np.array([d1,d2]) # making simpel 1d array
fro = np.fromiter(dic,dtype = np.int64)#agar koye dict ya str ko 1d array me convert kerna ho to

arange = np.arange(1,16,1)#making elemnt array (starting,ending value,step value)

linespace = np.linspace(1,10,15)#making elemnt array (starting,ending value,jitne value hame chaye)

empty_array = np.empty([3,5])#es se ham empty array banate hai take samaye ane per ham us me data fill ker sake

zeroes = np.zeros([3,5],dtype=np.int32,order = "f")#make array with all element '0'

ones = np.ones([3,5])#make array with all element '1'

eye = np.eye(5)#to make element '1' at diagonal and '0' at non-diagonal

full = np.full([5,5],"ankit")#making array with all same elemnt 

random_ran = np.random.rand(3,5)#make array of element between 0-1 ranondomly

random_ranint = np.random.randint(1,100,size=(5,5))#make element with randon no. given as input -->(start value,till value,size of array)

In [167]:
#some basic functions
shape = random_ranint.shape# yane ke array ke row or column me ketne element hai-->'.shape' shpe==(row,coulmn)
reshape = random_ranint.reshape(5,5)#to modify the the shape of array
itemsize = a1.itemsize#size of each element of array

In [168]:
#Accessing arrays
na = np.array([d1,d2,d3,d1])#maked new array
print(na[1,1])#to accsess perticular elemnt --->na[list no. , element no.]
print(na[1])#to print perticular list

#replacing of element
na[1,1] = 0

#slicing
#[starting place:ending place:select value] for 1-d
#same as string slicing in 2d

7
[6 7 8 9 0 2]


In [169]:
#concatin arrays
array1 = np.array([d1,d2])
array2 = np.array([d2,d1])
hstack = np.hstack((d1,d2))
vstack = np.vstack((d1,d2))
concate = np.concatenate((array1,array2),axis=0)#to concat column [default]
concate1 = np.concatenate((array1,array2),axis=1)#to concat row
#print(array1,"\n********\n",array2)
#print(concate1,"\n********\n",concate)

#split
hsplit = np.hsplit(na, 1)#agar horizontly array ke tokde kerne ho to
vsplit = np.vsplit(na,1)#agar verticaly array ke tukde keren ho to
split = np.split(na,[2,5],axis=0)

In [174]:
#maths on array
#1
#attributes
flat = array1.flat
'''for values in flat:
    print(values)'''
print(array2)
print(array2.ndim)#to print no. of dimenssion
print(array2.nbytes)#total bytes consumed by all elements
print(array2.argmax())#it tell wher max num is present
print(array2.argmin())#it tell wher min num is present
print(np.where(array2==1))#us jaghe ka nam batata hai jaha hamare condition satatisfy hoti hai

[[6 7 8 9 0 2]
 [1 2 3 4 5 3]]
2
48
3
4
(array([1], dtype=int64), array([0], dtype=int64))
