In [35]:
import numpy as np

In [43]:
np.random.seed(0)
X = [[1,2,3,4],
    [6,7,8,9],
    [10,11,12,13]]

In [44]:
class Layer_Dense:
    def __init__(self,n_input,n_nurons):#yane ke ek thrase LAyer_Dense ye 2 input le raha hai
        self.weight = np.random.randn(n_input,n_nurons)#randomly weight banade ga given (_,_) shape me
        self.biases = np.zeros((1,n_nurons))
    def forward (self,input):
        self.output = np.dot(input,self.weight) + self.biases
        # es ham input phele es liye le rahe hai take hame transpose mna kerna pade
        
        

In [45]:
#making matrix for nuron
layer1 = Layer_Dense(4,5) # Layer_Dense(no of feature of input , no. of nuron we want in output)
layer2 = Layer_Dense(5,3) #(_ , _ ) en me phele vo number dalana hai ke pechle nuron ketne the 


NOTE- numpy me matrix calulation kerne ke liye shape kuch es there hone chaye

(A,B)*(B,A) yane dusre matrix me phele 1st matrix ka dusra no. likhna hai(B)

In [51]:
#doing maths with data we date in form of matrix
#layer1.forward(X)
layer2.forward(layer1.output)

print(layer2.output)
layer1.output

[[ -8.47751481  28.68802335 -12.57109664]
 [-29.64612548  63.8027587  -26.14864612]
 [-46.58101401  91.89454697 -37.01068571]]


array([[ 1.57632461, 12.63947086,  2.13850369,  3.65175135,  0.60396174],
       [ 7.89878643, 34.13246189,  9.05480487, 16.51383668,  9.94358166],
       [12.95675589, 51.32685471, 14.58784582, 26.80350494, 17.4152776 ]])